title: Margaret Kapitany # your name (or website title) here
logo: "/images/headshot_square.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! ðŸ‘‹ Iâ€™m Margaret, recent BBA Honours (MIS, Operations & Marketing) graduate from SFU
  <br><br>
  I have 2+ years of work experience across business development, agile product development, and consulting in both client and internal facing roles. If anything on my profile interest you and youâ€™d like to chat more, letâ€™s connect!
  <br><br>
  <a href="https://www.linkedin.com/in/mgkapitany/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
