title: Margaret Kapitany # your name (or website title) here
logo: "/images/headshot_square.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello World!Hello! ðŸ‘‹ Iâ€™m Margaret, recent BBA graduate who is passionate about technology, business model innovation, and data. As a gamer at heart, Iâ€™m driven by curiosity and the excitement of finding solutions. I thrive in challenging situations and accomplish my best with dynamic & motivated individuals. Iâ€™m always learning and adapting from my failures.
  <br><br>
  My work experience spans various functions: business development, agile product development, and consulting in both client and internal facing roles. I love to embrace the complexities of data sets to find opportunities for process improvement, and I've gained a deep passion for delivering value through effective agile project management. Above all, I am loyal to user-focused innovation. Iâ€™m eager to embrace new opportunities in analytics, product development, and business process analysis â€“ if anything on my profile interest you and youâ€™d like to chat more, letâ€™s connect!
  <br><br>
  <a href="https://www.linkedin.com/in/mgkapitany/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
